<?php

return [
    'modules' => [
        [
            'key' => 'dashboard',
            'section' => 'Overview',
            'title' => 'Dashboard',
            'icon' => 'chart-area',
            'route' => 'user_dashboard',
            'status' => 'active',
            'stage' => 'Operate',
            'audience' => 'Everyone',
            'purpose' => 'A single command surface for next actions, owned work, and operational health.',
            'actions' => ['Review next actions', 'Open active workspaces', 'Monitor platform health'],
        ],
        [
            'key' => 'events',
            'section' => 'Events',
            'title' => 'Events',
            'icon' => 'calendar-heart',
            'route' => 'user.events',
            'admin_route' => 'admin.events.index',
            'permission' => null,
            'admin_permission' => ['event-view-any', 'event-create'],
            'status' => 'active',
            'stage' => 'Acquire',
            'audience' => 'Students, guests, speakers, admins',
            'purpose' => 'Public programs, event registration, attendee workspace, speakers, resources, and reminders.',
            'actions' => ['Browse events', 'Register or join waitlist', 'Manage attendees and resources'],
            'lms_bridge' => 'Events can later graduate into cohorts that grant LMS enrollment.',
            'children' => [
                [
                    'title' => 'My Events',
                    'route' => 'user.events',
                ],
                [
                    'title' => 'All Events',
                    'route' => 'admin.events.index',
                    'permission' => 'event-view-any',
                ],
                [
                    'title' => 'Create Event',
                    'route' => 'admin.events.create',
                    'permission' => 'event-create',
                ],
            ],
        ],
        [
            'key' => 'invitations',
            'section' => 'Events',
            'title' => 'My Invitations',
            'icon' => 'send',
            'route' => 'invitations.index',
            'permission' => 'view-own-invitations',
            'status' => 'active',
            'stage' => 'Engage',
            'audience' => 'Speakers',
            'purpose' => 'A focused inbox for speaker invitations tied to events.',
            'actions' => ['Review invitations', 'Accept speaking context', 'Open speaker workspace'],
        ],
        [
            'key' => 'mentorship',
            'section' => 'Mentorship',
            'title' => 'Mentorship',
            'icon' => 'user-group',
            'route' => 'student.mentorship.index',
            'admin_route' => 'admin.mentorship.index',
            'permission' => ['mentorship-view-own', 'mentorship-view-instructor', 'mentorship-manage-any'],
            'status' => 'active',
            'stage' => 'Deepen',
            'audience' => 'Students, instructors, admins',
            'purpose' => 'Structured mentorship requests, sessions, milestones, and resources.',
            'actions' => ['Request mentorship', 'Review requests', 'Track milestones'],
            'lms_bridge' => 'Mentorship can consume LMS progress signals later without becoming the course engine.',
            'children' => [
                [
                    'title' => 'My Mentorship',
                    'route' => 'student.mentorship.index',
                    'permission' => 'mentorship-view-own',
                ],
                [
                    'title' => 'Mentorship Requests',
                    'route' => 'instructor.mentorship.index',
                    'permission' => 'mentorship-view-instructor',
                ],
                [
                    'title' => 'Mentorship Manager',
                    'route' => 'admin.mentorship.index',
                    'permission' => 'mentorship-manage-any',
                ],
            ],
        ],
        [
            'key' => 'commerce',
            'section' => 'Commerce',
            'title' => 'Payments',
            'icon' => 'receipt',
            'route' => 'transactions.index',
            'admin_route' => 'admin.transactions-audit.index',
            'permission' => ['view-own-transaction-history', 'view-transaction-audit'],
            'status' => 'active',
            'stage' => 'Transact',
            'audience' => 'Students, admins',
            'purpose' => 'Receipts, paid event checkout, transaction review, and audit resolution.',
            'actions' => ['View receipts', 'Audit transactions', 'Resolve payment issues'],
            'children' => [
                [
                    'title' => 'Transaction History',
                    'route' => 'transactions.index',
                    'permission' => 'view-own-transaction-history',
                ],
                [
                    'title' => 'Transaction Audit',
                    'route' => 'admin.transactions-audit.index',
                    'permission' => 'view-transaction-audit',
                ],
            ],
        ],
        [
            'key' => 'support',
            'section' => 'Support',
            'title' => 'Support',
            'icon' => 'life-buoy',
            'route' => 'user.tickets.index',
            'admin_route' => 'admin.tickets.index',
            'permission' => null,
            'status' => 'active',
            'stage' => 'Support',
            'audience' => 'Students, admins',
            'purpose' => 'A shared place for user issues, admin replies, and ticket status.',
            'actions' => ['Open a ticket', 'Reply to users', 'Resolve issues'],
            'children' => [
                [
                    'title' => 'My Support Tickets',
                    'route' => 'user.tickets.index',
                    'exclude_permission' => 'manage-tickets',
                ],
                [
                    'title' => 'Support Manager',
                    'route' => 'admin.tickets.index',
                    'permission' => 'manage-tickets',
                ],
            ],
        ],
        [
            'key' => 'people',
            'section' => 'Administration',
            'title' => 'People & Access',
            'icon' => 'users-cog',
            'permission' => ['view-user-list', 'view-permission-list', 'manage-instructor-applications', 'create-speaker', 'view-speaker'],
            'status' => 'active',
            'stage' => 'Govern',
            'audience' => 'Admins',
            'purpose' => 'Users, roles, permissions, speakers, instructors, applications, and ratings.',
            'actions' => ['Manage users', 'Review applications', 'Control permissions'],
            'children' => [
                [
                    'title' => 'Speaker Manager',
                    'route' => 'admin.speakers.index',
                    'permission' => ['create-speaker', 'view-speaker'],
                ],
                [
                    'title' => 'Instructor Manager',
                    'route' => 'admin.instructors.index',
                    'permission' => 'manage-instructor-applications',
                ],
                [
                    'title' => 'User Management',
                    'route' => 'admin.users.index',
                    'permission' => 'view-user-list',
                ],
                [
                    'title' => 'Roles & Permissions',
                    'route' => 'admin.roles.index',
                    'permission' => 'view-permission-list',
                ],
            ],
        ],
        [
            'key' => 'content',
            'section' => 'Administration',
            'title' => 'Content & Settings',
            'icon' => 'settings',
            'permission' => ['manage-blog', 'manage-ratings', 'view-user-list'],
            'status' => 'active',
            'stage' => 'Govern',
            'audience' => 'Admins',
            'purpose' => 'Public content, ratings moderation, and platform settings.',
            'actions' => ['Publish posts', 'Moderate ratings', 'Update settings'],
            'children' => [
                [
                    'title' => 'Blog Manager',
                    'route' => 'admin.posts.index',
                    'permission' => 'manage-blog',
                ],
                [
                    'title' => 'Instructor Ratings',
                    'route' => 'admin.ratings.index',
                    'permission' => 'manage-ratings',
                ],
                [
                    'title' => 'Settings',
                    'route' => 'admin.settings',
                    'permission' => 'view-user-list',
                ],
            ],
        ],
        [
            'key' => 'lms',
            'section' => 'Learning',
            'title' => 'LMS',
            'icon' => 'book-open',
            'status' => 'planned',
            'stage' => 'Learn',
            'audience' => 'Students, instructors, admins',
            'purpose' => 'Courses, cohorts, lessons, assessments, progress, certificates, and learning resources.',
            'actions' => ['Design course catalog', 'Enroll learners', 'Track progress'],
            'lms_bridge' => 'Build as its own module. Connect to events through cohort enrollment and to mentorship through progress visibility.',
            'planned_permissions' => ['lms-view-catalog', 'lms-enroll-self', 'lms-manage-courses', 'lms-teach-cohorts'],
            'planned_routes' => ['learning.catalog', 'learning.my-courses', 'admin.learning.courses.index'],
        ],
    ],
];
